### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by thewhitetulip** [Birdbrain2/PdfBox-Android#11]
I want to contribute to this project, how can I do so?
There isn't any good pdf library available for android, it would be fun to make this library a good one :)
:+1:  for the effort.

**Comment by Birdbrain2** [comment]
You're welcome to contribute in any way you want to. If there's something specific you want for a project of yours, I would recommend working on that

**Comment by thewhitetulip** [comment]
I have plans to build a pdf reader/writer app for android with all the fancy feature like annotations, bookmarks, notes, highlights and extremely easy to use fully functional etc. I also plan to make the app as the central "convert to pdf" zone of android. That way you can send a web URL and it will convert it into pdf things like that, I don't have the bandwidth to clone your repo, so don't know how much you have done, is it possible for you to make the time to do some documentation? Or should I start with the docs?

**Comment by Birdbrain2** [comment]
There really aren't any docs to make. Almost all the methods and usages are the same as the ones in the original version. I would start working on whatever you can for your app, until you find something that isn't implemented yet or doesn't work correctly.

**Comment by thewhitetulip** [comment]
Okay, I'll need to read the original version's docs to understand the functionality before I start building the app and will submit a pull request when I face some issues.

Nice initiative though, android world was lacking an open source, full fledged and robust pdf library.
