### ISSUE TITLE
Output pdf file invalid

### ISSUE THREAD

**Issue by eduardojiang** [Birdbrain2/PdfBox-Android#16]
I am a beginner for this project. I created the hello world pdf. But it can not opened on the phone or on the PC. Please help to check about it. Thanks!

 I add this code in the button onClick() function:

<code>                   
 PDDocument document = new PDDocument();

				PDPage page = new PDPage();
				document.addPage( page );

				// Create a new font object selecting one of the PDF base fonts
				PDFont font = PDType1Font.HELVETICA_BOLD;

				// Start a new content stream which will "hold" the to be created content
				PDPageContentStream contentStream;
				try {
					contentStream = new PDPageContentStream(document, page);
					// Define a text content stream using the selected font, moving the cursor and drawing the text "Hello World"
					contentStream.beginText();
					contentStream.setFont( font, 12 );
					contentStream.moveTextPositionByAmount( 100, 700 );
					contentStream.drawString( "Hello World" );
					contentStream.endText();

					// Make sure that the content stream is closed:
					contentStream.close();

					// Save the results and ensure that the document is properly closed:
					document.save(Environment.getExternalStorageDirectory().getPath()
							+ "/Hello World.pdf");
					document.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
<code/>

using the newest pdfbox-android-1.8.8 jar library file in android sdk 19
UPDATE: pdfbox-android-1.8.7 work!!

**Comment by Birdbrain2** [comment]
Saving is fixed now. However, the text drawn out will have Ê instead of spaces.
