### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in android.graphics.Matrix.setValues

### ISSUE THREAD

**Issue by bomski** [Birdbrain2/PdfBox-Android#19]
# PDPageContentStream

The Android `Matrix` class needs 9 Values otherwise the `ArrayIndexOutOfBoundsException` is throw.
To create a correct `AffineTransform` with the Android `Matrix` class the following lines needs to be changed.

**Line: 483**

    transform.setValues(new float[] {width, 0, 0, height, x, y});  
must be replaced with

    transform.setValues(new float[] {width, 0, x, 0, height, y, 0, 0, 1 });

**Line: 618:**

    transform.setValues(new float[] {width, 0, 0, height, x, y}); 
must be replaced with

    transform.setValues(new float[] {width, 0, x, 0, height, y, 0, 0, 1 });

**Comment by bomski** [comment]
This was not working as aspect. So i wrote an helper class which simulate the AffineTransform class from java (`java.awt.geom.AffineTransform`)

    package org.apache.pdfbox.util;

    public class AffineTransform {

	private double m00, m10, m01, m11, m02, m12;
	
	public AffineTransform(){
		m00 = m11 = 1;
	}
	
	public AffineTransform(AffineTransform tx){
		setTransform(tx);
	}
	
	public AffineTransform(double m00, double m10, double m01, double m11, double m02, double m12){
		this.m00 = m00;
		this.m10 = m10;
		this.m01 = m01;
		this.m11 = m11;
		this.m02 = m02;
		this.m12 = m12;
	}
	
	public void setTransform(AffineTransform tx){
		m00 = tx.m00;
		m01 = tx.m01;
		m02 = tx.m02;
		m10 = tx.m10;
		m11 = tx.m11;
		m12 = tx.m12;
	}
	
	public double getScaleX(){
		return m00;
	}
	
	public double getShearY(){
		return m10;
	}
	
	public double getShearX(){
		return m01;
	}
	
	public double getScaleY(){
		return m11;
	}
	
	public double getTranslateX(){
		return m02;
	}
	
	public double getTranslateY(){
		return m12;
	}

	public void getMatrix(double[] values) {
		values[0] = m00;
		values[1] = m10;
		values[2] = m01;
		values[3] = m11;
		values[4] = m02;
		values[5] = m12;
	}
	
	public void transform(double[] srcPts, int srcOff, double[] dstPts, int dstOff, int num)
	{
		if (srcPts == dstPts && dstOff > srcOff
			&& num > 1 && srcOff + 2 * num > dstOff) {
			double[] d = new double[2 * num];
			System.arraycopy(srcPts, srcOff, d, 0, 2 * num);
			srcPts = d;
		}
		while (--num >= 0)
		{
			double x = srcPts[srcOff++];
			double y = srcPts[srcOff++];
			dstPts[dstOff++] = m00 * x + m01 * y + m02;
			dstPts[dstOff++] = m10 * x + m11 * y + m12;
		}
	}
	
	public void transform(float[] srcPts, int srcOff, float[] dstPts, int dstOff, int num)
	{
		if (srcPts == dstPts && dstOff > srcOff
			&& num > 1 && srcOff + 2 * num > dstOff) {
			float[] f = new float[2 * num];
			System.arraycopy(srcPts, srcOff, f, 0, 2 * num);
			srcPts = f;
		}
		while (--num >= 0)
		{
			float x = srcPts[srcOff++];
			float y = srcPts[srcOff++];
			dstPts[dstOff++] = (float) (m00 * x + m01 * y + m02);
			dstPts[dstOff++] = (float) (m10 * x + m11 * y + m12);
		}
	}
	
	public void scale(double sx, double sy){
		m00 *= sx;
		m01 *= sy;
		m10 *= sx;
		m11 *= sy;
	}
	
	public void translate(double tx, double ty){
		m02 += tx * m00 + ty * m01;
		m12 += tx * m10 + ty * m11;
	}
	
	public float[] transform(float[] src, float[] dst){
		if (dst == null)
			dst = new float[2];
		float x = src[0];
		float y = src[1];
		float nx = (float) (m00 * x + m01 * y + m02);
		float ny = (float) (m10 * x + m11 * y + m12);
		dst[0] = nx;
		dst[1] = ny;
		return dst;
	}
	
	public void rotate(double theta){
		double c = Math.cos(theta);
		double s = Math.sin(theta);
		double n00 = m00 *  c + m01 * s;
		double n01 = m00 * -s + m01 * c;
		double n10 = m10 *  c + m11 * s;
		double n11 = m10 * -s + m11 * c;
		m00 = n00;
		m01 = n01;
		m10 = n10;
		m11 = n11;
	}
	
	public boolean isIdentity(){
		return (m00 == 1 && m01 == 0 && m02 == 0
				&& m10 == 0 && m11 == 1 && m12 == 0);
	}
    }

=

And these additional changes are needed:

**PDFStreamEngine**

_Line 967:_ `getGraphicsState().getCurrentTransformationMatrix().createAffineTransform().mapPoints(position);` => `getGraphicsState().getCurrentTransformationMatrix().createAffineTransform().transform(position, 0, position, 0, 1);`

=

**PDCIDFontType0**

_Line 42:_
`private android.graphics.Matrix fontMatrixTransform;` => `private AffineTransform fontMatrixTransform;`

_Line 146:_
`fontMatrixTransform.setScale(1000, 1000);` => `fontMatrixTransform.scale(1000, 1000);`

_Line 266:_
`fontMatrixTransform.mapPoints(retval);` => `fontMatrixTransform.transform(retval, retval);`

=

**PDType1CFont**

_Line 38:_
`private final android.graphics.Matrix fontMatrixTransform;` => `private final AffineTransform fontMatrixTransform;`

_Line 111:_
`fontMatrixTransform.setScale(1000, 1000);` => `fontMatrixTransform.scale(1000, 1000);`

_Line 210:_
`fontMatrixTransform.mapPoints(retval);` => `fontMatrixTransform.transform(retval, retval);`

=

**PDFormXObject**

_Line 194:_

    public void setMatrix(android.graphics.Matrix transform)
    {
		COSArray matrix = new COSArray();
		float[] values = new float[9];
		transform.getValues(values);
		for (float v : values)
		{
			matrix.add(new COSFloat((float) v));
		}
		getCOSStream().setItem(COSName.MATRIX, matrix);
    }

=>

    public void setMatrix(AffineTransform transform)
    {
		COSArray matrix = new COSArray();
		double[] values = new double[6];
		transform.getMatrix(values);
		for (double v : values)
		{
			matrix.add(new COSFloat((float) v));
		}
		getCOSStream().setItem(COSName.MATRIX, matrix);
    }


**PDFTemplateBuilder**

_Line 181:_

    void createImageForm(PDResources imageFormResources, PDResources innerFormResource,
                                PDStream imageFormStream, PDRectangle formrect,
                                android.graphics.Matrix affineTransform, PDImageXObject img)
                                throws IOException;

=>

    void createImageForm(PDResources imageFormResources, PDResources innerFormResource,
                                PDStream imageFormStream, PDRectangle formrect,
                                AffineTransform affineTransform, PDImageXObject img)
                                throws IOException;

=

**PDVisibleSigBuilder**

_Line 273:_

    public void createImageForm(PDResources imageFormResources, PDResources innerFormResource, PDStream imageFormStream, PDRectangle formrect, android.graphics.Matrix at, PDImageXObject img) throws IOException

=>

    public void createImageForm(PDResources imageFormResources, PDResources innerFormResource, PDStream imageFormStream, PDRectangle formrect, AffineTransform at, PDImageXObject img) throws IOException

=

**PDPageContentStream**

_Line 383:_
`public void setTextMatrix(android.graphics.Matrix matrix) throws IOException` => `public void setTextMatrix(AffineTransform matrix) throws IOException`

_Line 483:_
`transform.setValues(new float[] {width, 0, 0, height, x, y});` => `AffineTransform transform = new AffineTransform(width, 0, 0, height, x, y);`

_Line 614:_

    public void drawXObject(PDXObject xobject, float x, float y, float width, float height) throws IOException
    {
    	android.graphics.Matrix transform = new android.graphics.Matrix();
    	transform.setValues(new float[] {width, 0, 0, height, x, y});
    	//AffineTransform transform = new AffineTransform(width, 0, 0, height, x, y); TODO
    	drawXObject(xobject, transform);
    }

=>

    public void drawXObject(PDXObject xobject, float x, float y, float width, float height) throws IOException
    {
    	AffineTransform transform = new AffineTransform(width, 0, 0, height, x, y);
    	drawXObject(xobject, transform);
    }

_Line 631:_
`public void drawXObject(PDXObject xobject, android.graphics.Matrix transform) throws IOException` =>
`public void drawXObject(PDXObject xobject, AffineTransform transform) throws IOException`

_Line 696:_
`public void concatenate2CTM(android.graphics.Matrix at) throws IOException` => `public void concatenate2CTM(AffineTransform at) throws IOException`

_Line 1952:_
`private void writeAffineTransform(android.graphics.Matrix transform) throws IOException` =>  `private void writeAffineTransform(AffineTransform transform) throws IOException`

=

**PageDrawer**

_Line 658:_

    public void drawImage(PDImage pdImage) throws IOException
    {
        org.apache.pdfbox.util.Matrix ctm = getGraphicsState().getCurrentTransformationMatrix();
        android.graphics.Matrix at = ctm.createAffineTransform();
        
        if (!pdImage.getInterpolate())
        {
        	float[] values = new float[9];
        	at.getValues(values);
        	boolean isScaledUp = pdImage.getWidth() < Math.round(values[Matrix.MSCALE_X]) ||
        	pdImage.getHeight() < Math.round(values[Matrix.MSCALE_X]);

        	// if the image is scaled down, we use smooth interpolation, eg PDFBOX-2364
        	// only when scaled up do we use nearest neighbour, eg PDFBOX-2302 / mori-cvpr01.pdf
        	// stencils are excluded from this rule (see survey.pdf)
        	if (isScaledUp || pdImage.isStencil())
        	{
        	    //graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
        	    //RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);
        	}
        }

        if (pdImage.isStencil())
        {
            // fill the image with paint
            //PDColor color = getGraphicsState().getNonStrokingColor();
            //Bitmap image = pdImage.getStencilImage(getPaint(color));

            // draw the image
            //drawBufferedImage(image, at);
        }
        else
        {
            // draw the image
            drawBufferedImage(pdImage.getImage(), at);
        }

        if (!pdImage.getInterpolate())
        {
        	// JDK 1.7 has a bug where rendering hints are reset by the above call to
        	// the setRenderingHint method, so we re-set all hints, see PDFBOX-2302
        	setRenderingHints();
        }
    }

=>

    public void drawImage(PDImage pdImage) throws IOException
    {
        org.apache.pdfbox.util.Matrix ctm = getGraphicsState().getCurrentTransformationMatrix();
        AffineTransform at = ctm.createAffineTransform();
        
        if (!pdImage.getInterpolate())
        {
        	boolean isScaledUp = pdImage.getWidth() < Math.round(at.getScaleX()) ||
        	pdImage.getHeight() < Math.round(at.getScaleY());

        	// if the image is scaled down, we use smooth interpolation, eg PDFBOX-2364
        	// only when scaled up do we use nearest neighbour, eg PDFBOX-2302 / mori-cvpr01.pdf
        	// stencils are excluded from this rule (see survey.pdf)
        	if (isScaledUp || pdImage.isStencil())
        	{
                   //graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                  //RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);
        	}
        }

        if (pdImage.isStencil())
        {
            // fill the image with paint
            //PDColor color = getGraphicsState().getNonStrokingColor();
            //Bitmap image = pdImage.getStencilImage(getPaint(color));

            // draw the image
            //drawBufferedImage(image, at);
        }
        else
        {
            // draw the image
            drawBufferedImage(pdImage.getImage(), at);
        }

        if (!pdImage.getInterpolate())
        {
        	// JDK 1.7 has a bug where rendering hints are reset by the above call to
        	// the setRenderingHint method, so we re-set all hints, see PDFBOX-2302
        	setRenderingHints();
        }
    }

_Line 703:_

    public void drawBufferedImage(Bitmap image, android.graphics.Matrix at) throws IOException
    {
        //graphics.setComposite(getGraphicsState().getNonStrokingJavaComposite());
        setClip();
        PDSoftMask softMask = getGraphicsState().getSoftMask();
        if( softMask != null )
        {
            android.graphics.Matrix imageTransform = new android.graphics.Matrix(at);
            imageTransform.postScale(1, -1);
            imageTransform.postTranslate(0, -1);
            //Paint awtPaint = new TexturePaint(image,
            // new Rectangle2D.Double(imageTransform.getTranslateX(), imageTransform.getTranslateY(),
            // imageTransform.getScaleX(), imageTransform.getScaleY()));
            //awtPaint = applySoftMaskToPaint(awtPaint, softMask);
            //graphics.setPaint(awtPaint);
            RectF unitRect = new RectF(0, 0, 1, 1);
            //graphics.fill(at.createTransformedShape(unitRect));
        }
        else
        {
            int width = image.getWidth();
            int height = image.getHeight();
            android.graphics.Matrix imageTransform = new android.graphics.Matrix(at);
            imageTransform.postScale((1.0f / width), (-1.0f / height));
            imageTransform.postTranslate(0, -height);
            //graphics.drawImage(image, imageTransform, null);
        }
    }

=>

    public void drawBufferedImage(Bitmap image, AffineTransform at) throws IOException
    {
        //graphics.setComposite(getGraphicsState().getNonStrokingJavaComposite());
        setClip();
        PDSoftMask softMask = getGraphicsState().getSoftMask();
        if( softMask != null )
        {
            AffineTransform imageTransform = new AffineTransform(at);
            imageTransform.scale(1, -1);
            imageTransform.translate(0, -1);
            //Paint awtPaint = new TexturePaint(image,
            //new Rectangle2D.Double(imageTransform.getTranslateX(), imageTransform.getTranslateY(),
            //imageTransform.getScaleX(), imageTransform.getScaleY()));
            //awtPaint = applySoftMaskToPaint(awtPaint, softMask);
            //graphics.setPaint(awtPaint);
            RectF unitRect = new RectF(0, 0, 1, 1);
            //graphics.fill(at.createTransformedShape(unitRect));
        }
        else
        {
            int width = image.getWidth();
            int height = image.getHeight();
            AffineTransform imageTransform = new AffineTransform(at);
            imageTransform.scale((1.0f / width), (-1.0f / height));
            imageTransform.translate(0, -height);
            //graphics.drawImage(image, imageTransform, null);
        }
    }

=

**LayerUtility**
_Line 131:

    public PDFormXObject importPageAsForm(PDDocument sourceDoc, PDPage page) throws IOException
	{
		COSStream pageStream = (COSStream)page.getStream().getCOSObject();
		PDStream newStream = new PDStream(targetDoc,
				pageStream.getUnfilteredStream(), false);
		PDFormXObject form = new PDFormXObject(newStream);

		//Copy resources
		PDResources pageRes = page.getResources();
		PDResources formRes = new PDResources();
		cloner.cloneMerge(pageRes, formRes);
		form.setResources(formRes);

		//Transfer some values from page to form
		transferDict(page.getCOSObject(), form.getCOSStream(), PAGE_TO_FORM_FILTER, true);

		Matrix matrix = form.getMatrix();
		android.graphics.Matrix at = matrix.createAffineTransform();
		PDRectangle mediaBox = page.getMediaBox();
		PDRectangle cropBox = page.getCropBox();
		PDRectangle viewBox = (cropBox != null ? cropBox : mediaBox);

		//Handle the /Rotation entry on the page dict
		int rotation = page.getRotation();

		//Transform to FOP's user space
		//at.scale(1 / viewBox.getWidth(), 1 / viewBox.getHeight());
		at.setTranslate(mediaBox.getLowerLeftX() - viewBox.getLowerLeftX(),
				mediaBox.getLowerLeftY() - viewBox.getLowerLeftY());
		switch (rotation)
		{
		case 90:
			at.setScale(viewBox.getWidth() / viewBox.getHeight(), viewBox.getHeight() / viewBox.getWidth());
			at.setTranslate(0, viewBox.getWidth());
			at.setRotate((float)(-Math.PI / 2.0));
			break;
		case 180:
			at.setTranslate(viewBox.getWidth(), viewBox.getHeight());
			at.setRotate((float)-Math.PI);
			break;
		case 270:
			at.setScale(viewBox.getWidth() / viewBox.getHeight(), viewBox.getHeight() / viewBox.getWidth());
			at.setTranslate(viewBox.getHeight(), 0);
			at.setRotate((float)(-Math.PI * 1.5));
		default:
			//no additional transformations necessary
		}
		//Compensate for Crop Boxes not starting at 0,0
		at.setTranslate(-viewBox.getLowerLeftX(), -viewBox.getLowerLeftY());
		if (!at.isIdentity())
		{
			form.setMatrix(at);
		}

		BoundingBox bbox = new BoundingBox();
		bbox.setLowerLeftX(viewBox.getLowerLeftX());
		bbox.setLowerLeftY(viewBox.getLowerLeftY());
		bbox.setUpperRightX(viewBox.getUpperRightX());
		bbox.setUpperRightY(viewBox.getUpperRightY());
		form.setBBox(new PDRectangle(bbox));

		return form;
	}

=>

    public PDFormXObject importPageAsForm(PDDocument sourceDoc, PDPage page) throws IOException
	{
		COSStream pageStream = (COSStream)page.getStream().getCOSObject();
		PDStream newStream = new PDStream(targetDoc,
				pageStream.getUnfilteredStream(), false);
		PDFormXObject form = new PDFormXObject(newStream);

		//Copy resources
		PDResources pageRes = page.getResources();
		PDResources formRes = new PDResources();
		cloner.cloneMerge(pageRes, formRes);
		form.setResources(formRes);

		//Transfer some values from page to form
		transferDict(page.getCOSObject(), form.getCOSStream(), PAGE_TO_FORM_FILTER, true);

		Matrix matrix = form.getMatrix();
		AffineTransform at = matrix.createAffineTransform();
		PDRectangle mediaBox = page.getMediaBox();
		PDRectangle cropBox = page.getCropBox();
		PDRectangle viewBox = (cropBox != null ? cropBox : mediaBox);

		//Handle the /Rotation entry on the page dict
		int rotation = page.getRotation();

		//Transform to FOP's user space
		//at.scale(1 / viewBox.getWidth(), 1 / viewBox.getHeight());
		at.translate(mediaBox.getLowerLeftX() - viewBox.getLowerLeftX(),
				mediaBox.getLowerLeftY() - viewBox.getLowerLeftY());
		switch (rotation)
		{
		case 90:
			at.scale(viewBox.getWidth() / viewBox.getHeight(), viewBox.getHeight() / viewBox.getWidth());
			at.translate(0, viewBox.getWidth());
			at.rotate((float)(-Math.PI / 2.0));
			break;
		case 180:
			at.translate(viewBox.getWidth(), viewBox.getHeight());
			at.rotate((float)-Math.PI);
			break;
		case 270:
			at.scale(viewBox.getWidth() / viewBox.getHeight(), viewBox.getHeight() / viewBox.getWidth());
			at.translate(viewBox.getHeight(), 0);
			at.rotate((float)(-Math.PI * 1.5));
		default:
			//no additional transformations necessary
		}
		//Compensate for Crop Boxes not starting at 0,0
		at.translate(-viewBox.getLowerLeftX(), -viewBox.getLowerLeftY());
		if (!at.isIdentity())
		{
			form.setMatrix(at);
		}

		BoundingBox bbox = new BoundingBox();
		bbox.setLowerLeftX(viewBox.getLowerLeftX());
		bbox.setLowerLeftY(viewBox.getLowerLeftY());
		bbox.setUpperRightX(viewBox.getUpperRightX());
		bbox.setUpperRightY(viewBox.getUpperRightY());
		form.setBBox(new PDRectangle(bbox));

		return form;
	}

_Line 207:_

    public PDOptionalContentGroup appendFormAsLayer(PDPage targetPage,
			PDFormXObject form, android.graphics.Matrix transform,
			String layerName) throws IOException
	{
		PDDocumentCatalog catalog = targetDoc.getDocumentCatalog();
		PDOptionalContentProperties ocprops = catalog.getOCProperties();
		if (ocprops == null)
		{
			ocprops = new PDOptionalContentProperties();
			catalog.setOCProperties(ocprops);
		}
		if (ocprops.hasGroup(layerName))
		{
			throw new IllegalArgumentException("Optional group (layer) already exists: " + layerName);
		}

		PDOptionalContentGroup layer = new PDOptionalContentGroup(layerName);
		ocprops.addGroup(layer);

		PDPageContentStream contentStream = new PDPageContentStream(
				targetDoc, targetPage, true, !DEBUG);
		contentStream.beginMarkedContent(COSName.OC, layer);
		contentStream.saveGraphicsState();
		contentStream.transform(new Matrix(transform));
		contentStream.drawForm(form);
		contentStream.restoreGraphicsState();
		contentStream.endMarkedContent();
		contentStream.close();

		return layer;
	}

=>

    public PDOptionalContentGroup appendFormAsLayer(PDPage targetPage,
			PDFormXObject form, AffineTransform transform,
			String layerName) throws IOException
	{
		PDDocumentCatalog catalog = targetDoc.getDocumentCatalog();
		PDOptionalContentProperties ocprops = catalog.getOCProperties();
		if (ocprops == null)
		{
			ocprops = new PDOptionalContentProperties();
			catalog.setOCProperties(ocprops);
		}
		if (ocprops.hasGroup(layerName))
		{
			throw new IllegalArgumentException("Optional group (layer) already exists: " + layerName);
		}

		PDOptionalContentGroup layer = new PDOptionalContentGroup(layerName);
		ocprops.addGroup(layer);

		PDPageContentStream contentStream = new PDPageContentStream(
				targetDoc, targetPage, true, !DEBUG);
		contentStream.beginMarkedContent(COSName.OC, layer);
		contentStream.saveGraphicsState();
		contentStream.transform(new Matrix(transform));
		contentStream.drawForm(form);
		contentStream.restoreGraphicsState();
		contentStream.endMarkedContent();
		contentStream.close();

		return layer;
	}

=

**Matrix**

_Line 66:_

    public Matrix(android.graphics.Matrix at)
	{
		float[] values = new float[9];
		at.getValues(values);
		single[0] = (float)values[android.graphics.Matrix.MSCALE_X];
		single[1] = (float)values[android.graphics.Matrix.MSKEW_Y];
		single[3] = (float)values[android.graphics.Matrix.MSKEW_X];
		single[4] = (float)values[android.graphics.Matrix.MSCALE_Y];
		single[6] = (float)values[android.graphics.Matrix.MTRANS_X];
		single[7] = (float)values[android.graphics.Matrix.MTRANS_Y];
		//TODO do we need to fill in  0/1s?
	}

=>

    public Matrix(AffineTransform at)
	{
        single = new float[DEFAULT_SINGLE.length];
        System.arraycopy(DEFAULT_SINGLE, 0, single, 0, DEFAULT_SINGLE.length);
        single[0] = (float)at.getScaleX();
        single[1] = (float)at.getShearY();
        single[3] = (float)at.getShearX();
        single[4] = (float)at.getScaleY();
        single[6] = (float)at.getTranslateX();
        single[7] = (float)at.getTranslateY();
	}

_Line 96:_

    public android.graphics.Matrix createAffineTransform()
	{
		android.graphics.Matrix retval = new android.graphics.Matrix();
		//        		(
		//            single[0], single[1],
		//            single[3], single[4],
		//            single[6], single[7] );
		retval.setValues(single);
		return retval;
		// TODO wrong, and will be wrong in other areas
	}

=>

    public AffineTransform createAffineTransform()
	{
		return new AffineTransform(
	            single[0], single[1],   // m00 m10 = scaleX shearY
	            single[3], single[4],   // m01 m11 = shearX scaleY
	            single[6], single[7] ); // m02 m12 = tx ty
	}

_Line 115:_

    public void setFromAffineTransform( android.graphics.Matrix af )
	{
		float[] values = new float[9];
		af.getValues(values);
		single[0] = (float)values[android.graphics.Matrix.MSCALE_X];
		single[1] = (float)values[android.graphics.Matrix.MSKEW_Y];
		single[3] = (float)values[android.graphics.Matrix.MSKEW_X];
		single[4] = (float)values[android.graphics.Matrix.MSCALE_Y];
		single[6] = (float)values[android.graphics.Matrix.MTRANS_X];
		single[7] = (float)values[android.graphics.Matrix.MTRANS_Y];
	}

=>

    public void setFromAffineTransform( AffineTransform af )
	{
		single[0] = (float)af.getScaleX();
        single[1] = (float)af.getShearY();
        single[3] = (float)af.getShearX();
        single[4] = (float)af.getScaleY();
        single[6] = (float)af.getTranslateX();
        single[7] = (float)af.getTranslateY();
	}

=

**Overlay**

_Line 407:_
`xobjForm.setMatrix(new android.graphics.Matrix());` => `xobjForm.setMatrix(new AffineTransform());`

**Comment by Birdbrain2** [comment]
Well thank you. I've been meaning to do something like this for a while now. I'll get to work implementing it right away.

**Comment by camdenfullmer** [comment]
There is also a problem when the ```PDPageContentStream``` writes out a transform with the provided android.graphics.Matrix. Instead of just writing the 6 values that are necessary it writes all 9 of the matrix and screws up the generated PDF.

I was going to do a pull request, but if Matrix is replaced with AffineTransform then it should be correct.
