### ISSUE TITLE
PDF Form filling invisible text

### ISSUE THREAD

**Issue by Darksearcher** [Birdbrain2/PdfBox-Android#22]
When giving values to an acorform pdf and then saving said pdf and transferring to PC.  Clicking a form field in adobe reader shows the text in the field , but it will not show if it is not clicked.  Upon research of this, it seems as PDFBox is corrupting/damaging the pdf file.  Ironically using Adobe Reader on Android, displays the PDF correctly.

**Comment by Birdbrain2** [comment]
I thought that I had this fixed a while ago. I'll look into it.

**Comment by Darksearcher** [comment]
Thank you for looking into this, please let me know if I am mistaken and if there is something on my side that was done incorrectly.

**Comment by wathy** [comment]
Can you please provide a sample of code?

**Comment by Darksearcher** [comment]
So the first sample below, is my way of searching through the fields of a PDF given an input stream.  I'm checking to see if the name of the editTexts and other UI elements match the ones in the PDF, if they do then I write onto the PDF Fields what is written from the android UI.  There are a lot of commented lines I should have removed, these are just things I was trying out.  (Note: I may be missing curly brackets near the end by accident, I cut out some of the other "if statements" as I am trying to transition from another library to PDFbox)

```java
public class PdfWriter2 {

public static PDDocument viewToPdf (ViewGroup viewGroup, InputStream inputStream){

        LinkedList<String> DebugList = new LinkedList<>();

        try
        {
            PDDocument pdfDoc = PDDocument.load(inputStream);
            PDDocumentCatalog pdfCat = pdfDoc.getDocumentCatalog();
            //PDAcroForm pdfDoc = new PDAcroForm(PDDocument.load(inputStream));

            PDAcroForm pdfDoc2 = pdfCat.getAcroForm();
            //PDResources formresources = pdfDoc2.getDefaultResources();

            //pdfDoc2.setCacheFields(true);

            List<PDFieldTreeNode> form = pdfDoc2.getFields();

            //PDFDocument pdfDoc = new PDFDocument(inputStream,null);
            //AcroForm form = pdfDoc.getAcroForm();

            for (int i = 0, count = viewGroup.getChildCount(); i < count; ++i) {
                View anElement = viewGroup.getChildAt(i);

                if(form == null)
                {
                    Log.e("", "document does not contain form fields");
                }
                else
                {
                    //print current values of all textfields, set the value of "field1"


                    for(int k = 0; k < form.size(); k++)
                    {
                        PDFieldTreeNode field = form.get(k);

                        Log.e("", "The id is " + anElement.getId() + " And is type: " + field.getFieldType());

                        String AndroidElement = viewGroup.getResources().getResourceEntryName(anElement.getId());
                        String PdfElement = field.getFullyQualifiedName();

                        //Debuging

                        if (PdfElement.equals(AndroidElement) ) {


                            DebugList.add("The android element is equal to Pdf Element with the name: " + AndroidElement + " " +PdfElement + " PDFElement is of type: " + field.getFieldType() );

                        }


                        if ((field.getFieldType()).equals("Tx") && anElement instanceof EditText && AndroidElement.equals(PdfElement)) {


                            Log.e("", field.getFullyQualifiedName()  + " " + field.getValue() + " " + viewGroup.getResources().getResourceEntryName(anElement.getId()));
                            //form.get(k).setValue("IT WORKS");

                            //((PDVariableText)field).setRichTextValue(((EditText) anElement).getText().toString());

                            //field.setValue(((EditText) anElement).getText().toString());
                            PDFieldTreeNode changeField = pdfDoc2.getField( AndroidElement );
                            changeField.setValue(((EditText) anElement).getText().toString());

                        }

                }

            }
            for (int i = 0; i < DebugList.size(); i++) {
                Log.e("",DebugList.get(i));
            }

            return pdfDoc;

        }catch (Throwable t)
        {
            Log.e("", Log.getStackTraceString(t));
        }



        return null;
    }
```


So the function above is the one being called in the segment below, again I've removed a couple parts that are irrelevant to the problem.

```java
public void toEducation(View view)
    {       
        Intent intent = new Intent(this,EducationalBackground.class);
        ViewGroup group = (ViewGroup)findViewById(R.id.firstPage);
        InputStream firstForm = getResources().openRawResource(R.raw.employment_application_di);

       try {
            PDDocument pdfDoc = PdfWriter2.viewToPdf(group,firstForm);
            pdfDoc.save(getExternalFilesDir(null).toString() + "/PDFBOX2.pdf");
            firstForm.close();
            pdfDoc.close();

        }catch (Throwable t)
        {
            Log.e("", Log.getStackTraceString(t));
            Toast toast = Toast.makeText(getApplicationContext(),t.getMessage(),Toast.LENGTH_LONG);
            toast.show();
        }



        startActivity(intent);

    }

```

If I am missing a call of a function or if there is anything that stands out that shouldn't be done, please let me know.

**Comment by Birdbrain2** [comment]
Your code looks alright. I can confirm that this is an issue.

**Comment by Darksearcher** [comment]
Is there something that I can do to accelerate fixing this bug?  It is pretty vital for the current project I'm working on.

**Comment by Birdbrain2** [comment]
I've been pretty busy for the last couple weeks so I haven't had much time to work on this. I should have more time to work on it now, and I'll make this a priority. I can't think of anything you can do to help, but I'll let you know if there's anything you can do. 

-----Original Message-----

**Comment by Birdbrain2** [comment]
Update: it seems like a couple of the values of the forms are being parsed in as null instead of having an actual value. Hopefully getting those fixed will resolve this issue.

**Comment by Darksearcher** [comment]
Hey great, I'm looking forward to trying it but currently I am getting the following when trying to fill the fields on the PDF. 

```java
04-07 00:33:41.967    3476-3814/com.dixieind.dixieapplication E/﹕ java.lang.IllegalArgumentException: No glyph for U+0041 in font Helvetica
```

All I've done is changed the pdfbox-android-1.8.8.jar in my project.  Is that not enough?  I've reverted to the old one in the meantime (compiling and working without errors).

**Comment by Birdbrain2** [comment]
I would advise staying with the jar version that works. The unicode mapping already has an issue report under Issue #31.

**Comment by Darksearcher** [comment]
Any chance of this getting fixed?  My only alternative for filling forms then, would be to flatten down a PDF.  Once a pdf has been filled I'd like to print it.  Obviously the issue with this is that you can't change any information on the form afterwards.

**Comment by nakoned** [comment]
Not to brag about it, but the bug re-appeared in the latest 2.0.2 version, while in 1.8.12 it appears to be working. Could you please move your changes to the latest version?
Thanks

**Comment by heidenthal** [comment]
I know this is closed, but I am having this issue in 2.05 - any insights?

**Comment by urswiss** [comment]
I too have this issue in version 2.0.11, any updates?

**Comment by urswiss** [comment]
I'm not sure if the issue is related to this project (PdfBox-
Android), since we are using the source http://svn.apache.org/repos/asf/pdfbox/ (in a Java project on the backend)
