### ISSUE TITLE
Unknown Problem

### ISSUE THREAD

**Issue by Darksearcher** [Birdbrain2/PdfBox-Android#23]
I hate to add this here, but I'm very desperate to solve this problem.  If anyone could help me with this that would be great, I'm not sure if its an android issue, or a PdfBox issue.

http://stackoverflow.com/questions/28464200/my-app-wont-run-on-my-other-android-devices-advanced-issues

Any help is greatly appreciated.

**Comment by Birdbrain2** [comment]
Definitely a PdfBox issue. Update to the latest version and you should be good. I'm surprised that it worked on any of your devices actually.

-----Original Message-----

**Comment by Darksearcher** [comment]
Brilliant, all my devices are working now using pdfbox.  Seeing the changes that were done to this project, I find it hard to believe that my one tablet was working as well, pretty strange.  Anyway thank you very much for all the help!
