### ISSUE TITLE
Add library to jcenter

### ISSUE THREAD

**Issue by camdenfullmer** [Birdbrain2/PdfBox-Android#24]
Allow developers to include this library through a dependency in gradle.

**Comment by Birdbrain2** [comment]
This sounds like a good idea to me. Thanks for working on the setup for gradle. I haven't used gradle in a while, so let me familiarize myself with it before I do the pull and setup the dependency.

**Comment by camdenfullmer** [comment]
Sounds good. I was thinking then next step would be to add a sample project along with a few test cases as well.

**Comment by Birdbrain2** [comment]
I have a couple files that I can clean up and use for a sample project. The desktop test cases can probably be ported over to be used on Android.

**Comment by camdenfullmer** [comment]
So, then all we have to do to add it to jCenter is create an account and bundle up the project. I found this [script](https://github.com/blundell/release-android-library) that will package the library up for us.

**Comment by Birdbrain2** [comment]
I've got the script all setup and building. The only problem is that the Javadocs aren't building properly. The names of the library and sample folders need to be named PdfBox-Android and PdfBox-Android-Sample. Can you make a pull request with those renames? As you can tell from the last two commits, I tried, but git didn't rename all the files properly. You don't have to worry about editing the scripts, I've got those already ready

**Comment by camdenfullmer** [comment]
Yea, I will submit a pull request later today

**Comment by camdenfullmer** [comment]
@Birdbrain2 what is the reason behind them having to be named that?

**Comment by Birdbrain2** [comment]
It's recommended to have Javadocs released with a library especially with one add large as this. Gradle pulls the name of the project into the Javadocs, so without changing the name, it would show library instead of actually displaying the proper name.

-Tom Roush

-----Original Message-----

**Comment by camdenfullmer** [comment]
Ok, was just curious about this. I will get those changes submitted soon.

**Comment by camdenfullmer** [comment]
Can't you rename what Javadocs uses for the project name?

Here are two example libraries that use the "library" and "sample" naming conventions and also have a maven script with them as well:
- https://github.com/loopj/android-async-http
- https://github.com/gabrielemariotti/cardslib

**Comment by Birdbrain2** [comment]
Yes, you're completely right. I've made the necessary changes in Gradle.

**Comment by jitpack-io** [comment]
Btw, in the mean time the its possible to add the dependency using: https://jitpack.io/#Birdbrain2/PdfBox-Android/e48d0a6914

**Comment by thorinii** [comment]
Has this been pushed to an official repository yet? There's no mention of it in the Readme.

**Comment by thorinii** [comment]
Has this been published to a public repo yet? I see no mention of it in the Readme.

**Comment by Birdbrain2** [comment]
Thanks for reminding me to do this. The files are now uploaded to Bintray and I've requested to have them added to the Jcenter repository.

**Comment by thorinii** [comment]
np thanks

**Comment by Birdbrain2** [comment]
It's been accepting into jcenter. You can add ``` org.apache:pdfbox-android:1.8.9.0 ``` to your dependencies list if you have jcenter added as a repository. Thanks so much @camdenfullmer for your help.
