### ISSUE TITLE
PDType1Font should use encoding field instead of MacOSRomanEncoding.INSTANCE

### ISSUE THREAD

**Issue by Albert78** [Birdbrain2/PdfBox-Android#27]
In PDType1Font#getInvertedEncoding(), the MacOSRomanEncoding is inverted and used to look up non-ASCII-characters but the field "encoding" should be used here.
You can test it with when you write a german string with umlauts to a PDF.

Class PDTrueTypeFont also uses a hard coded reference to MacOSRomanEncoding but here I can't judge if it's also incorrect. It would be worth an examination.

**Comment by Birdbrain2** [comment]
Yes, that is an issue. It'll be fixed in the next update
