### ISSUE TITLE
Standard14Fonts#addAFM is missing short-cut return statement

### ISSUE THREAD

**Issue by Albert78** [Birdbrain2/PdfBox-Android#28]
In Standard14Fonts#addAFM(String, String), in the shortcut check "if (STANDARD14_AFM_MAP.containsKey(afmName))", a return statement is missing. Else, the rest of the method will be executed as if the shortcut check was not met.

**Comment by Birdbrain2** [comment]
This seems right, I'll test and make sure. You may want to put this on the desktop version's issue tracker as well

**Comment by Birdbrain2** [comment]
I haven't been able to find any cases where adding the return statement messing things up, but I'm hesitant to make this change as it could causes problems later. If this is truly a mistake and it gets changed in the desktop version, I'll copy the changes over.
