### ISSUE TITLE
Unable to parse file

### ISSUE THREAD

**Issue by archanaasankar** [Birdbrain2/PdfBox-Android#30]
Hi ,I have used this jar and i am unable to parse pdf file.I am getting following error message.

Could not find method java.io.IOException.<init>, referenced from method org.apache.pdfbox.pdfparser.BaseParser.readLong

Could not find method java.io.IOException.<init>, referenced from method org.apache.pdfbox.pdfparser.BaseParser.parseCOSString

Can you tell me what would be the reason for this

**Comment by Birdbrain2** [comment]
What code caused this error? Was it just using the load function? Did you download the jar or use the gradle build? The gradle build may have had an error that caused this.

**Comment by archanaasankar** [comment]
This is the code i am using.	
PDFParser parser;
File file = new File(sdcard,"ac123002.pdf");
FileInputStream fin = new FileInputStream(file);
parser = new PDFParser(fin);


I am getting exception in this PDFParser constructor

**Comment by Birdbrain2** [comment]
Are you targeting API levels >= 9 (Gingerbread or above)? Two of the methods in IOException were added in level 9.

**Comment by Birdbrain2** [comment]
Are you targeting API levels >= 9 (Gingerbread or above)? Two of the methods in IOException were added in level 9.

**Comment by archanaasankar** [comment]
Hi  Thanks that resolved error.

Now I am using the  lib project instead of the jar ,I am facing issue in reading text file from resources folder.

I am getting null exception while reading text file from resources folder
can you help me where the problem is

**Comment by Birdbrain2** [comment]
The Gradle build currently isn't building the resources folders into the jars. For now, use the jar, but Gradle should be fixed very soon.

**Comment by archanaasankar** [comment]
If i use jar in android studio,I am not able to build , it shows error.

**Comment by camdenfullmer** [comment]
What is the error you are seeing?

**Comment by Birdbrain2** [comment]
Gradle should be properly building resources into the jar now. I would still like to know what kind of error you're getting when you try to use the prebuilt jar.
