### ISSUE TITLE
GlyphList.loadList Error in 1.8.8

### ISSUE THREAD

**Issue by dun74fr** [Birdbrain2/PdfBox-Android#31]
Hi  Birdbrain2,
I am using pdfbox-android for few month now in my android app.
I am facing a problem with the extraction of text on Korean files. I tried to upgrade to 1.8.8 to see if there is any improvements. But when using 1.8.8 I always crash with this error : 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
            at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.loadList(GlyphList.java:104)

I am probably doing something wrong but I've got no problem with 1.8.7 and 1.8.6.

**Comment by dun74fr** [comment]
Hi,
I managed to get it working using the library project without the jar.
It didn't solve my problem with korean pdfs. 
I am trying to extract text and highlight parts, but the every character send me  

W/PdfBoxAndroid﹕ No Unicode mapping for c158 (3) in font GCIIFN+WtKoBaeumGothicL01cc5BUbM

At the end the extracted text is full of unicode codes.

**Comment by AedonEtLIRA** [comment]
@dun74fr What was your solution the the GlyphList exception? I just started experiencing that yesterday as well.

**Comment by dun74fr** [comment]
@AedonEtLIRA
I only stopped using the jar file and linked my project directly on the library project from pdfbox-android.

**Comment by Birdbrain2** [comment]
The current jar has an issue where the glyphlist resource was built in correctly. Building with Gradle or the new jar (released in a day most likely) should resolve this. The unicode mapping issue should hopefully be fixed shortly. As for the text extraction in Korean, it mostly likely will not work. See issue #18 for this problem

**Comment by dun74fr** [comment]
Thanks for the information.
Regarding the Korean text extraction, I also submitted a bug on PDFBox because there is the same problem.
I tried to investigate, in PDType1CFont the tounicode code, but it quite difficult to understand the way the font is encoded.
Other tools like Xpdf can extract the text, but the code is too far to try to copy the implementation.

**Comment by Birdbrain2** [comment]
The unicode mapping issue is an issue with desktop PdfBox at the version that the library is currently at. Upgrading the code should get that fixed
