### ISSUE TITLE
INSTALL_FAILED_CPU_ABI_INCOMPATIBLE for 1.8.9 on Genymotion

### ISSUE THREAD

**Issue by crspl** [Birdbrain2/PdfBox-Android#33]
Hi,

Not sure whether it's bug or just lack of my knowledge but when I add 1.8.9 library version to my project I cannot run my app in Genymotion emulator. My IDE (IntelliJ Idea) gives me message INSTALL_FAILED_CPU_ABI_INCOMPATIBLE. When I replace lib with version 1.8.7 everything runs ok and I can use library features in my project.

**Comment by Birdbrain2** [comment]
I looked up the error, and it sounds like it could be related to the naming of the library folder in the prebuilt jar. Try building the jar with Gradle and see if that works better
