### ISSUE TITLE
Google play supported device 0

### ISSUE THREAD

**Issue by Anastasion** [Birdbrain2/PdfBox-Android#36]
Have a problem with an already-published application on Google Play.
The application is in the store, but no one can download, because of an error Supported devices 0.
I did refactor the project, removed all unnecessary with the manifest. Compiled a new apk, and again "Supported devices 0".
I use pdfbox-android-1.8.9.jar.
If I remove the pdfbox from project, then are "Supported devices 7700".
I build project with Eclipse.

What does this mean?

**Comment by camdenfullmer** [comment]
This might have to do with your ```AndroidManifest.xml``` file or it could be the way the .jar was packaged. To fix this you could probably just include the source instead of using the .jar.

**Comment by Anastasion** [comment]
Thanks. This solved problem.

**Comment by Birdbrain2** [comment]
This is definitely a problem with the way the jar is packaged. If you're using the sources, you may want to try running a Gradle build. Since it compiles the .class files, your apk should be a bit smaller.
