### ISSUE TITLE
No glyph for U+000A in font Helvetica

### ISSUE THREAD

**Issue by agustinsivoplas** [Birdbrain2/PdfBox-Android#41]
I am trying to generate a PDF but I always have this issue:

    java.lang.IllegalArgumentException: No glyph for U+000A in font Helvetica
            at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:290)
            at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:249)
            at org.apache.pdfbox.pdmodel.PDPageContentStream.showText(PDPageContentStream.java:292)

Another thing, always take aprox 30 segs to generate a pdf.
I think is because the look for al ttf in the system. It is possible to do more fast?

All the best

**Comment by ashokkumarsand** [comment]
facing the same issue

**Comment by TomRoush** [comment]
Were you using the latest jar in the Releases section? This is a known issue in the jar. For current, working code, you should be getting the library through jCenter or building it through Gradle.

**Comment by ralfhauser** [comment]
http://stackoverflow.com/questions/34553148/cant-insert-tabs-and-spaces-into-pdbox-pdf-document
