### ISSUE TITLE
writing simple to text in gingerbread

### ISSUE THREAD

**Issue by vinodatphp** [Birdbrain2/PdfBox-Android#43]
writing a simple hello world to pdf using drawString takes nearly 20 minutes in android gingerbread with ram 343

**Comment by Birdbrain2** [comment]
I pushed changes that should help with this today. Put this line: ``` PDFBoxResourceLoader.init(getApplicationContext()); ``` somewhere in your code before you use PDFBox methods. This library does still use quite a bit of ram, so it may still take a while, but it should go faster.
