### ISSUE TITLE
Drawing transparent images

### ISSUE THREAD

**Issue by Dzuum** [Birdbrain2/PdfBox-Android#44]
Does the library at the moment support drawing transparent images? I have a png with transparent background I need to draw.

At the moment I draw my pngs and jpgs by first loading them up into Bitmap objects and then using the following function to transform them into PDImageXObjects:

<code>
private PDImageXObject getImageXObjectFromBitmap(PDDocument doc, Bitmap bitmap) throws IOException {
		
		PDImageXObject image = null;

		if (image != null)
			return image;
		
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		bitmap.compress(CompressFormat.JPEG, 100, baos);
		byte[] bytes = baos.toByteArray();
		InputStream imageStream = new ByteArrayInputStream(bytes);
		
		image = JPEGFactory.createFromStream(doc, imageStream);
		
		baos.close();
		imageStream.close();
		
		return image;
}
</code>

**Comment by Birdbrain2** [comment]
Right now it shouldn't do transparency. The only method of creating images for PDFBox right now is to use the JPEGFactory, which won't preserve the transparency of the image. I'll look into getting the png factory working.
