### ISSUE TITLE
possible : PdfBox not generating a valid edited pdf

### ISSUE THREAD

**Issue by PetarAnastasov** [Birdbrain2/PdfBox-Android#45]
Im developing an app that is used to preview pdf files and add hand signature to them.
Im using two 3rd party libs: PdfBox (for editing) and MuPdf port for Android (for preview).

What i basically do is take a pdf file (not edited) from assets, show it to the user (using MuPdf), and then the user can (on button click) add a hand signature (inside different activity). I capture the signature bitmap and save the image on the SDCARD. After that i have a method insertImage (this is the ONLY piece of code in my app related to this library) like this 

public static void insertImage(Context context) {
    String pdfPath = context.getFilesDir() + File.separator + "/myPdf.pdf";
    int marginFromEdge = 40;

    PDDocument doc;
    try {
      doc = PDDocument.load(new File(pdfPath));
      PDPage page = doc.getPage(0);

      File imageFile = new File(Environment.getExternalStorageDirectory() + "/PdfDir/image.jpg");
      File pdfFile = new File(Environment.getExternalStorageDirectory() + "/PdfDir/myPdfEdited.pdf");

      PDImageXObject pdImage = JPEGFactory.createFromStream(doc,
        new FileInputStream(imageFile));

      PDPageContentStream contentStream = new PDPageContentStream(doc, page, true, true);
      contentStream.drawImage(pdImage,
        page.getCropBox().getWidth() - pdImage.getWidth() - marginFromEdge, marginFromEdge);
      contentStream.close();

      doc.save(pdfFile);
      doc.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

Now everything is working GREAT! Except when i go back from the signature activity i can't see the image that was inserted in the pdf, i see the pdf as it was before the signature.

When i open myPdfEdited.pdf with android adobe native viewer (or ANY other pdf viewer) i can see the signature but not with MuPdf, so i thought this was a MuPdf issue. But then i tried to add the same image in the pdf using a PC pdf editor and preview that image using my app and i can see the signature which tells me that MuPdf is working as it should. Maybe im not setting some parameter on the PDDocument...

So i thought maybe this is PdfBox issue because i can open every edited pdf file and preview it with MuPdf except the one that is saved in insertImage method by PdfBox doc.save(pdfFile).

I hope you understand my problem and i hope you can help.

Thanks.

**Comment by PetarAnastasov** [comment]
Sorry i forgot to mention... im using pdfbox-android-1.8.7.jar

**Comment by PetarAnastasov** [comment]
After some research i found out that the PDocument.save method generates invalid .pdf file. Maybe there is something that is wrong with the metadata fields or the structure of the pdf file because when i repair the file with PC pdf repair tool i can view it with the hand signature with MuPdf. So is there a way i can set some default (or valid) metadata fields so that the pdf is in valid format. By the way when i run a scan on the pdf file (with this tool http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx) i get the following log 

The key Metadata is required but missing.
A device-specific color space (DeviceGray) without an appropriate output intent is used.
A device-specific color space (DeviceRGB) without an appropriate output intent is used.
The operator has an invalid number of operands.
The key S has a value Transparency which is prohibited.
The font Times New Roman,Bold must be embedded.
The font Times New Roman must be embedded.
The font Times New Roman,Italic must be embedded.
The document does not conform to the requested standard.
The document contains device-specific color spaces.
The document contains fonts without embedded font programs or encoding information (CMAPs).
The document contains transparency.
The document's meta data is either missing or inconsistent or corrupt.

**Comment by PetarAnastasov** [comment]
Ok. First of all i would like to apologize for opening this issue. I was using version 1.8.7 jar from the releases which was not the latest... This issue is gone in the newest library. The rendering is perfect. 

But if someone else bumped into a problem with the rendering just include this project as a library and thats it.

Again, very sorry for opening this issue. The lib is working as it should.

**Comment by Birdbrain2** [comment]
No problem, I'm just glad that you got it working the way it should.
