### ISSUE TITLE
Is PDFRenderer working now?

### ISSUE THREAD

**Issue by jyosh** [Birdbrain2/PdfBox-Android#46]
I saw couple of commits related to PDFRenderer, is it working now? I tried following code but didn't give any output

            InputStream inputStream = assetManager.open("Test.pdf");
            PDDocument pdDocument = PDDocument.load(inputStream);;
            PDFRenderer pdfRenderer = new PDFRenderer(pdDocument);
            Bitmap pageBitmap = pdfRenderer.renderImage(0);
            ImageView imageView = (ImageView)findViewById(R.id.imageView);
            imageView.setImageBitmap(pageBitmap);

If it is working now please provide a sample code for how to use it

**Comment by Birdbrain2** [comment]
I've made some progress, but it still isn't done yet. If you try to render, you should still probably be getting a white/black blank image.
