### ISSUE TITLE
Load external TTF fonts?

### ISSUE THREAD

**Issue by teknogeek** [Birdbrain2/PdfBox-Android#47]
Hello, I notice that there are a lot of "No TTF fallback font for xxxx" errors showing up and I was wondering if I could load a TTF file into PDFBox so that it could use that instead of throwing an error. Is this possible or is there any way around this?

**Comment by Birdbrain2** [comment]
So you're loading a custom font into PDFBox and it's giving you fallback errors when you try to use it? What code are you using to load in the font?

**Comment by teknogeek** [comment]
no. i want to know if it is possible, and if so, how

**Comment by Birdbrain2** [comment]
Yes, it's possible. If you have your TTF font in your assets folder and a PDDocument called document, 
```
PDFont font = PDTrueTypeFont.loadTTF(document, getAssets().open("font.ttf"));
```

That will create the font from the file you specified.
