### ISSUE TITLE
GlyphLoading fails

### ISSUE THREAD

**Issue by pixelmyr** [Birdbrain2/PdfBox-Android#48]
It appears glyph loading from a file fails when there is a blank line at the end of the file. Around like 116 in GlyphList.java, the function `ready()` is used to determine if there are any more characters left in the stream. This function returns 'true' at the end of the file, even when garbage will be parsed and returned as `null`. 

Research shows that `ready()` checks if parsing will cause a block of the main thread, instead of actually seeing if the stream is still valid. Therefore, its use here is problematic.

**Comment by Birdbrain2** [comment]
You're correct, the ready() function doesn't work the way I thought it did, thanks for bringing this to my attention. There were some resource files that are included in your pull request and shouldn't have been, please resubmit without the resources and I'll accept your request.

**Comment by Birdbrain2** [comment]
Fixes merged in
