### ISSUE TITLE
Question: Is it possible to create a PDF/A conform file with this pdfbox port?

### ISSUE THREAD

**Issue by BaN4NaJ0e** [Birdbrain2/PdfBox-Android#53]
Is it somehow possible to create a [PDF/A] (https://en.wikipedia.org/wiki/PDF/A) like described here:
https://pdfbox.apache.org/1.8/cookbook/pdfacreation.html

Are these classes used in the cookbook already ported? I can't figure out how to adapt this tutorial to my android app.

**Comment by Birdbrain2** [comment]
No, those classes haven't been ported yet.
