### ISSUE TITLE
Draw fill rectangle

### ISSUE THREAD

**Issue by thuanict** [Birdbrain2/PdfBox-Android#9]
Hello,

Can I draw a fill rectangle with this lib? In the Apache's PdfBox, there is a method fillRect() able to draw a fill rectangle, but I don't see it in this lib.

**Comment by Birdbrain2** [comment]
fillRect has been added, but for now the only color that can be drawn is black. If that's the color you need, good. Otherwise I'll get to working on porting the color system

**Comment by Birdbrain2** [comment]
Rectangles can be drawn in any color. The current method is to call addRect and then fill, but you can use fillRect as well.
